### ISSUE TITLE
Extension activation error: Cannot get Typescript APIs

### ISSUE THREAD

**Issue by petekp** [denoland/vscode_deno#189]
I'm setting up Deno for the first time in a new project and the VSCode extension host log shows this error:

```
[2020-08-30 14:35:30.746] [exthost] [error] Activating extension denoland.vscode-deno failed due to an error:
[2020-08-30 14:35:30.753] [exthost] [error] Error: Cannot get typescript APIs. try restart Visual Studio Code.
    at getTypescriptAPI (/Users/petepetrash/.vscode/extensions/denoland.vscode-deno-2.0.16/client/out/client/src/extension.js:31:17)
    at Extension.activate (/Users/petepetrash/.vscode/extensions/denoland.vscode-deno-2.0.16/client/out/client/src/extension.js:268:28)
    at Function._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:877:509)
    at Function._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:877:160)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:875:492
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Promise.all (index 2)
```
I've tried the following steps to fix the issue to no avail:
- Reinstalled Deno
- Reinstalled Typescript
- Reinstalled VSCode
- Reinstalled VSCode Deno extension

**Versions**

vscode: `1.48.2`
deno: `1.3.2`
node: `11.4.0`
extension: `2.2.0`
tsc: `4.0.2`
OS: MacOS Catalina `10.15.6`

**Comment by CGQAQ** [comment]
> I'm setting up Deno for the first time in a new project and the VSCode extension host log shows this error:
> 
> ```
> [2020-08-30 14:35:30.746] [exthost] [error] Activating extension denoland.vscode-deno failed due to an error:
> [2020-08-30 14:35:30.753] [exthost] [error] Error: Cannot get typescript APIs. try restart Visual Studio Code.
>     at getTypescriptAPI (/Users/petepetrash/.vscode/extensions/denoland.vscode-deno-2.0.16/client/out/client/src/extension.js:31:17)
>     at Extension.activate (/Users/petepetrash/.vscode/extensions/denoland.vscode-deno-2.0.16/client/out/client/src/extension.js:268:28)
>     at Function._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:877:509)
>     at Function._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:877:160)
>     at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:875:492
>     at processTicksAndRejections (internal/process/task_queues.js:85:5)
>     at async Promise.all (index 2)
> ```
> 
> I've tried the following steps to fix the issue to no avail:
> 
> * Reinstalled Deno
> * Reinstalled Typescript
> * Reinstalled VSCode
> * Reinstalled VSCode Deno extension
> 
> **Versions**
> 
> vscode: `1.48.2`
> deno: `1.3.2`
> node: `11.4.0`
> extension: `2.2.0`
> tsc: `4.0.2`
> OS: MacOS Catalina `10.15.6`

You have a 2.0.16 vscode-deno installed according to the log, please double check your vscode deno plug-in version

**Comment by petekp** [comment]
@CGQAQ I'm now for sure running `vscode-deno-2.2.0` but getting the same error:

```
[2020-09-08 10:53:54.543] [exthost] [error] Activating extension denoland.vscode-deno failed due to an error:
[2020-09-08 10:53:54.549] [exthost] [error] Error: Cannot get typescript APIs. try restart Visual Studio Code.
    at getTypescriptAPI (/Users/petepetrash/.vscode/extensions/denoland.vscode-deno-2.2.0/client/out/client/src/extension.js:44:17)
    at Extension.activate (/Users/petepetrash/.vscode/extensions/denoland.vscode-deno-2.2.0/client/out/client/src/extension.js:282:28)
    at Function._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:877:509)
    at Function._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:877:160)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:875:492
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Promise.all (index 2)
```

**Comment by CGQAQ** [comment]
Can you take a look at your builtin `vscode.typescript-language-features` is enabled or not?
![issue4](https://user-images.githubusercontent.com/15936231/92681792-2f599a00-f361-11ea-8850-ef0c9bba5b6d.gif)

**Comment by petekp** [comment]
@CGQAQ This was indeed the problem! I thought I had double checked this but apparently the TypeScript and JavaScript Language Features extension needed to be enabled for this specific workspace.

Thank you for your help. The screencap was very useful!

**Comment by CGQAQ** [comment]
@petekp Please close your issue, I don't have permission

**Comment by YuriyTigiev** [comment]
I have a similar problem and I don't know how to solve it.  

![image](https://github.com/denoland/vscode_deno/assets/22752322/a5645c49-2c2d-4b8f-8160-18874d29639f)



Remote server - Almalinux 

VSC

```
Version: 1.80.1 (user setup)
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:22:07.651Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```

Deno

```
deno --version
deno 1.35.2 (release, x86_64-unknown-linux-gnu)
v8 11.6.189.7
typescript 5.1.6

```

**Comment by yeonjulee1005** [comment]
@YuriyTigiev  
hello my friend !
could you find solution?? i have same problem :cry:
