### ISSUE TITLE
Extension doesn't work

### ISSUE THREAD

**Issue by Igorgro** [denoland/vscode_deno#262]
### test

Intellisense, autocompletion, coloring doesn't work or working badly.

**To Reproduce**

1. Install deno
2. Install vscode deno extension and configure it as it is said in Readme
3. Create sample ts file (see screenshot)
4. See intellisense not working and wrong colors in editor
5. An error log in vscode "Deno Language server" appears:
```
(node:316) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.normalize (path.js:266:5)
    at parseNonShell (c:\Users\user\.vscode\extensions\denoland.vscode-deno-2.3.3\server\node_modules\cross-spawn\lib\parse.js:49:31)
    at Function.parse [as _parse] (c:\Users\user\.vscode\extensions\denoland.vscode-deno-2.3.3\server\node_modules\cross-spawn\lib\parse.js:88:37)
    at handleArguments (c:\Users\user\.vscode\extensions\denoland.vscode-deno-2.3.3\server\node_modules\execa\index.js:28:28)
    at Object.execa [as default] (c:\Users\user\.vscode\extensions\denoland.vscode-deno-2.3.3\server\node_modules\execa\index.js:75:17)
    at Deno.lint (c:\Users\user\.vscode\extensions\denoland.vscode-deno-2.3.3\server\out\server\src\deno.js:112:43)
    at Diagnostics.lint (c:\Users\user\.vscode\extensions\denoland.vscode-deno-2.3.3\server\out\server\src\language\diagnostics.js:91:46)
    at Diagnostics.generate (c:\Users\user\.vscode\extensions\denoland.vscode-deno-2.3.3\server\out\server\src\language\diagnostics.js:112:49)
    at async Diagnostics.diagnosis (c:\Users\user\.vscode\extensions\denoland.vscode-deno-2.3.3\server\out\server\src\language\diagnostics.js:160:26)
(node:316) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:316) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:316) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.normalize (path.js:266:5)
    at parseNonShell (c:\Users\user\.vscode\extensions\denoland.vscode-deno-2.3.3\server\node_modules\cross-spawn\lib\parse.js:49:31)
    at Function.parse [as _parse] (c:\Users\user\.vscode\extensions\denoland.vscode-deno-2.3.3\server\node_modules\cross-spawn\lib\parse.js:88:37)
    at handleArguments (c:\Users\user\.vscode\extensions\denoland.vscode-deno-2.3.3\server\node_modules\execa\index.js:28:28)
    at Object.execa [as default] (c:\Users\user\.vscode\extensions\denoland.vscode-deno-2.3.3\server\node_modules\execa\index.js:75:17)
    at Deno.lint (c:\Users\user\.vscode\extensions\denoland.vscode-deno-2.3.3\server\out\server\src\deno.js:112:43)
    at Diagnostics.lint (c:\Users\user\.vscode\extensions\denoland.vscode-deno-2.3.3\server\out\server\src\language\diagnostics.js:91:46)
    at Diagnostics.generate (c:\Users\user\.vscode\extensions\denoland.vscode-deno-2.3.3\server\out\server\src\language\diagnostics.js:112:49)
    at async Diagnostics.diagnosis (c:\Users\user\.vscode\extensions\denoland.vscode-deno-2.3.3\server\out\server\src\language\diagnostics.js:160:26)
(node:316) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:316) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.normalize (path.js:266:5)
    at parseNonShell (c:\Users\user\.vscode\extensions\denoland.vscode-deno-2.3.3\server\node_modules\cross-spawn\lib\parse.js:49:31)
    at Function.parse [as _parse] (c:\Users\user\.vscode\extensions\denoland.vscode-deno-2.3.3\server\node_modules\cross-spawn\lib\parse.js:88:37)
    at handleArguments (c:\Users\user\.vscode\extensions\denoland.vscode-deno-2.3.3\server\node_modules\execa\index.js:28:28)
    at Object.execa [as default] (c:\Users\user\.vscode\extensions\denoland.vscode-deno-2.3.3\server\node_modules\execa\index.js:75:17)
    at Deno.lint (c:\Users\user\.vscode\extensions\denoland.vscode-deno-2.3.3\server\out\server\src\deno.js:112:43)
    at Diagnostics.lint (c:\Users\user\.vscode\extensions\denoland.vscode-deno-2.3.3\server\out\server\src\language\diagnostics.js:91:46)
    at Diagnostics.generate (c:\Users\user\.vscode\extensions\denoland.vscode-deno-2.3.3\server\out\server\src\language\diagnostics.js:112:49)
    at async Diagnostics.diagnosis (c:\Users\user\.vscode\extensions\denoland.vscode-deno-2.3.3\server\out\server\src\language\diagnostics.js:160:26)
(node:316) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
```

**Expected behavior**

Autocompletion and colors works normally

**Screenshots**

![image](https://user-images.githubusercontent.com/22894169/100216377-4309ab00-2f23-11eb-9501-4f2f560e545d.png)

**Versions**

vscode: 1.51.1
deno: 1.5.4
extension: 2.3.3

**Comment by kitsonk** [comment]
Please try again with extension version 3.0.1 and Deno 1.7.5.
