### ISSUE TITLE
Connection to language server got closed unexpectedly

### ISSUE THREAD

**Issue by finalwhy** [denoland/vscode_deno#298]
### test

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
> Info  - 下午6:50:12] Connection to server got closed. Server will restart.
[Error - 下午6:50:12] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\45180\.vscode\extensions\denoland.vscode-deno-canary-0.0.6\client\node_modules\vscode-jsonrpc\lib\main.js:904:25)
	at Object.dispose (c:\Users\45180\.vscode\extensions\denoland.vscode-deno-canary-0.0.6\client\node_modules\vscode-languageclient\lib\client.js:74:35)
	at LanguageClient.handleConnectionClosed (c:\Users\45180\.vscode\extensions\denoland.vscode-deno-canary-0.0.6\client\node_modules\vscode-languageclient\lib\client.js:2309:42)
	at LanguageClient.handleConnectionClosed (c:\Users\45180\.vscode\extensions\denoland.vscode-deno-canary-0.0.6\client\node_modules\vscode-languageclient\lib\main.js:155:15)
	at closeHandler (c:\Users\45180\.vscode\extensions\denoland.vscode-deno-canary-0.0.6\client\node_modules\vscode-languageclient\lib\client.js:2296:18)
	at CallbackList.invoke (c:\Users\45180\.vscode\extensions\denoland.vscode-deno-canary-0.0.6\client\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\45180\.vscode\extensions\denoland.vscode-deno-canary-0.0.6\client\node_modules\vscode-jsonrpc\lib\events.js:121:36)
	at closeHandler (c:\Users\45180\.vscode\extensions\denoland.vscode-deno-canary-0.0.6\client\node_modules\vscode-jsonrpc\lib\main.js:240:26)
	at CallbackList.invoke (c:\Users\45180\.vscode\extensions\denoland.vscode-deno-canary-0.0.6\client\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\45180\.vscode\extensions\denoland.vscode-deno-canary-0.0.6\client\node_modules\vscode-jsonrpc\lib\events.js:121:36)
	at StreamMessageReader.fireClose (c:\Users\45180\.vscode\extensions\denoland.vscode-deno-canary-0.0.6\client\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at Socket.<anonymous> (c:\Users\45180\.vscode\extensions\denoland.vscode-deno-canary-0.0.6\client\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
	at Socket.emit (events.js:228:7)
	at Pipe.<anonymous> (net.js:664:12)

**Versions**

vscode: 1.52.1
deno: 1.6.3
extension: canary 0.0.6

**Comment by kitsonk** [comment]
@finalwhy can you provide steps to reproduce?  It looks like you were typing something in an open document.

Also, there should be output in the `Deno Language Server` that should be visible too which will provide more information about the failure:

![commands_ts_—_vscode_deno](https://user-images.githubusercontent.com/1282577/103763652-4178ea00-506e-11eb-8f3a-987fd5e7725a.png)

**Comment by finalwhy** [comment]
Actually，i don't konw how to reproduce this problem。 Usually， i'm just typing an 'import' or other code words and this problem will appear，and  the output screenchut is here 
![vscode_deno_error](https://user-images.githubusercontent.com/24859256/103765055-82b1cf80-5057-11eb-9033-4fc8b3a6fb54.png)
