### ISSUE TITLE
Deno LSP spins up and errors without being asked to when editing .tsx file (carany 0.0.6)

### ISSUE THREAD

**Issue by David-Else** [denoland/vscode_deno#299]
There is no `.vscode/settings.json` file in the project, so the Deno extension should not be running.

```
Starting Deno language server...
  version: 1.6.3 (release, x86_64-unknown-linux-gnu)
Connected to "vscode" 1.52.1
language server initialized
Server ready.
thread 'main' panicked at 'assertion failed: self.is_char_boundary(n)', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/string.rs:1561:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 16:05:02] Connection to server got closed. Server will restart.
[Error - 16:05:02] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (/home/david/.vscode/extensions/denoland.vscode-deno-canary-0.0.6/client/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/home/david/.vscode/extensions/denoland.vscode-deno-canary-0.0.6/client/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/home/david/.vscode/extensions/denoland.vscode-deno-canary-0.0.6/client/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/home/david/.vscode/extensions/denoland.vscode-deno-canary-0.0.6/client/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/david/.vscode/extensions/denoland.vscode-deno-canary-0.0.6/client/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/home/david/.vscode/extensions/denoland.vscode-deno-canary-0.0.6/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/david/.vscode/extensions/denoland.vscode-deno-canary-0.0.6/client/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/david/.vscode/extensions/denoland.vscode-deno-canary-0.0.6/client/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/home/david/.vscode/extensions/denoland.vscode-deno-canary-0.0.6/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/david/.vscode/extensions/denoland.vscode-deno-canary-0.0.6/client/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageReader.fireClose (/home/david/.vscode/extensions/denoland.vscode-deno-canary-0.0.6/client/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.<anonymous> (/home/david/.vscode/extensions/denoland.vscode-deno-canary-0.0.6/client/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:228:7)
	at Pipe.<anonymous> (net.js:664:12)
Starting Deno language server...
  version: 1.6.3 (release, x86_64-unknown-linux-gnu)
Connected to "vscode" 1.52.1
language server initialized
Server ready.
```
vscode: 1.52.1
deno: 1.6.3
extension: carany 0.0.6

**Comment by ry** [comment]
Not supported yet JSX/TSX are not supported yet - but will be soon.

-> https://github.com/denoland/deno/issues/8993
