### ISSUE TITLE
Autocomplete and most of extension breaks randomly

### ISSUE THREAD

**Issue by naturecodevoid** [denoland/vscode_deno#357]
**Describe the bug**

Seemly randomly the extension breaks with the errors "Unable to get quick info: Error: The current snapshot version is missing." and error code -32603. It also says "Request textDocument/hover failed."

**To Reproduce**

After some testing I'm still not sure why it breaks. I think it comes from switching to/saving a file in a different language. It may also somehow be related to tsc/sass/nodemon being run in the terminal 🤔 

**Expected behavior**

Nothing should break and the extension should run as expected.

**Versions**

vscode: 1.53.2
deno: 1.8.0
extension: 3.1.0

**Comment by kitsonk** [comment]
Can you provide the whole stack trace of one of the examples?

**Comment by naturecodevoid** [comment]
Here you go:

```
Unable to get quick info: Error: The current snapshot version is missing.
  Args: "GetChangeRangeArgs { specifier: "https://deno.land/x/getfiles@v1.0.0/utils.ts", old_length: 1643, old_version: "1614890744912", version: "1614891098383" }"
    at processResponse (deno:core/core.js:212:11)
    at Object.jsonOpSync (deno:core/core.js:236:12)
    at ScriptSnapshot.getChangeRange (deno:cli/tsc/99_main_compiler.js:224:19)
    at acquireOrUpdateDocument (deno:cli/tsc/00_typescript.js:123008:133)
    at Object.updateDocumentWithKey (deno:cli/tsc/00_typescript.js:122974:20)
    at Object.getOrCreateSourceFileByPath [as getSourceFileByPath] (deno:cli/tsc/00_typescript.js:149726:49)
    at tryReuseStructureFromOldProgram (deno:cli/tsc/00_typescript.js:107087:28)
    at Object.createProgram (deno:cli/tsc/00_typescript.js:106618:29)
    at synchronizeHostData (deno:cli/tsc/00_typescript.js:149648:26)
    at Object.getQuickInfoAtPosition (deno:cli/tsc/00_typescript.js:149810:13)
[Error - 12:52:01 PM] Request textDocument/hover failed.
  Message: Internal error
  Code: -32603 
```

**Comment by naturecodevoid** [comment]
I believe this is the same problem as #356. I will close the issue now.
