### ISSUE TITLE
`break` or `continue` in a function appear to panic the language server

### ISSUE THREAD

**Issue by somebody1234** [denoland/vscode_deno#375]
### test

**Describe the bug**
See title. Backtrace here, full Rust backtrace can be provided if I can figure out how.
```
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_lint-0.2.19/src/control_flow.rs:264:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(...)', cli/lsp/diagnostics.rs:118:4
[Error - 7:15:07 PM] Connection to server got closed. Server will not be restarted.
[Error - 7:15:07 PM] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (/root/.local/share/code-server/extensions/denoland.vscode-deno-3.2.0/client/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/root/.local/share/code-server/extensions/denoland.vscode-deno-3.2.0/client/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/root/.local/share/code-server/extensions/denoland.vscode-deno-3.2.0/client/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/root/.local/share/code-server/extensions/denoland.vscode-deno-3.2.0/client/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/root/.local/share/code-server/extensions/denoland.vscode-deno-3.2.0/client/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/root/.local/share/code-server/extensions/denoland.vscode-deno-3.2.0/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/root/.local/share/code-server/extensions/denoland.vscode-deno-3.2.0/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/root/.local/share/code-server/extensions/denoland.vscode-deno-3.2.0/client/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/root/.local/share/code-server/extensions/denoland.vscode-deno-3.2.0/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/root/.local/share/code-server/extensions/denoland.vscode-deno-3.2.0/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageReader.fireClose (/root/.local/share/code-server/extensions/denoland.vscode-deno-3.2.0/client/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
	at Socket.<anonymous> (/root/.local/share/code-server/extensions/denoland.vscode-deno-3.2.0/client/node_modules/vscode-jsonrpc/lib/common/messageReader.js:125:42)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:674:12)
```

**To Reproduce**

1. Type the following in any file:
```ts
function foo() {
  break;
}
```
Exports (including default exports), functions in objects, arrow functions and also `continue` rather than `break` appear to produce the same problem. Unknown if there are other cases in which this error occurs.

**Expected behavior**
No error

**Screenshots**

**Versions**

vscode: code-server 1.53.2
deno: 1.8.1
extension: 3.2.0

**Comment by lucacasonato** [comment]
Looking at the error it seems this should also happen when trying to `deno lint` this file.

**Comment by somebody1234** [comment]
can confirm
