### ISSUE TITLE
Error with .svelte file

### ISSUE THREAD

**Issue by mizchi** [denoland/vscode_deno#379]
### test

**Describe the bug**

Error with `.svelte` importing ts code

```
[Error - 4:07:49] Request textDocument/hover failed.
  Message: Internal error
  Code: -32603 
Unable to get quick info: Error: The current snapshot version is missing.
  Args: "GetChangeRangeArgs { specifier: "file:///Users/mizchi/gh/github.com/mizchi/swdev/example/App.svelte", old_length: 156, old_version: "1616871816788", version: "1616871974028" }"
    at processResponse (deno:core/core.js:212:11)
    at Object.jsonOpSync (deno:core/core.js:236:12)
    at ScriptSnapshot.getChangeRange (deno:cli/tsc/99_main_compiler.js:224:19)
    at acquireOrUpdateDocument (deno:cli/tsc/00_typescript.js:123008:133)
    at Object.updateDocumentWithKey (deno:cli/tsc/00_typescript.js:122974:20)
    at getOrCreateSourceFileByPath (deno:cli/tsc/00_typescript.js:149726:49)
    at Object.getOrCreateSourceFile [as getSourceFile] (deno:cli/tsc/00_typescript.js:149683:24)
    at findSourceFileWorker (deno:cli/tsc/00_typescript.js:108104:29)
    at findSourceFile (deno:cli/tsc/00_typescript.js:108014:26)
    at processImportedModules (deno:cli/tsc/00_typescript.js:108386:25)
```

Sample Code

```ts
// index.ts
import App from "./App.svelte";

export default () => {
  const target = document.querySelector(".svelte-root")!;
  new App({ target });
};
```

**To Reproduce**

1. enable deno exetension by `.vscode/settings.json` 's `dene.enable: true`
2. Put `App.svelte`
3. Put `index.ts` including `import App from "./App.svelte"`;
4. Open `index.ts` on vscode
5. Emit errors by each mouse move.

3. ...

**Expected behavior**

No error.

Ideally vscode-deno works with https://github.com/sveltejs/language-tools/tree/master/packages/language-server

**Screenshots**

![image](https://user-images.githubusercontent.com/73962/112743936-ad685000-8fd6-11eb-8799-e613bf87412a.png)

**Versions**

vscode: 1.54.3
deno: 1.8.1
extension: 3.2.0

**Comment by kitsonk** [comment]
We can possibly improve the error but `deno run index.ts` won't work, so I am not sure why it would be expected that the Deno LSP would work.
