### ISSUE TITLE
Failed to request to tsserver Error: Debug Failure. False expression.

### ISSUE THREAD

**Issue by nikolalukovic** [denoland/vscode_deno#396]
I had this code open and started getting vscode errors while writing it.
```
const { writeSync } = Deno.stdout;

const { encode } = new TextEncoder();

const w = writeSync.bind(Deno.stdout);
w(encode("bla bla bla"));
console.log();
Deno.stdout.writeSync(encode("bla bla bla"));
```
This is the error:
```
Failed to request to tsserver Error: Debug Failure. False expression.
    at checkChangeRange (deno:cli/tsc/00_typescript.js:35753:26)
    at Object.updateSourceFile (deno:cli/tsc/00_typescript.js:35344:13)
    at Object.updateSourceFile (deno:cli/tsc/00_typescript.js:28823:47)
    at updateLanguageServiceSourceFile (deno:cli/tsc/00_typescript.js:149411:40)
    at SyntaxTreeCache.getCurrentSourceFile (deno:cli/tsc/00_typescript.js:149360:30)
    at Object.getOutliningSpans (deno:cli/tsc/00_typescript.js:150060:46)
    at serverRequest (deno:cli/tsc/99_main_compiler.js:681:27)
    at [native_code]:1:12
[Error - 7:33:26 AM] Request textDocument/foldingRange failed.
  Message: Invalid request
  Code: -32600 
  ```

VSCode version:
```
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:36:32.643Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
```
Deno version:
```
deno 1.9.0 (release, x86_64-apple-darwin)
v8 9.1.269.5
typescript 4.2.2
```
Extension version:
```
3.3.0 / 2021.04.13
```

**Comment by jtremback** [comment]
Same here

**Comment by kitsonk** [comment]
There have been several updates to Deno and the extension dealing with some of these problems.

Does the problem still occur with current versions of Deno and the extension?

**Comment by nikolalukovic** [comment]
I've tested right now with 
```
deno 1.12.1 (release, x86_64-apple-darwin)
v8 9.2.230.14
typescript 4.3.5
```
and extension
```
3.7.0
```

And no exceptions popping for me 👍
