### ISSUE TITLE
Using any PIKA.DEV package causes TypeScript language service to die. TS Server fatal error:  Maximum call stack size exceeded

### ISSUE THREAD

**Issue by IgorSzymanski** [denoland/vscode_deno#41]
This plugin struggles with TS types received via `X-TypeScript-Types` in response header, and will cause TypeScript language service to die if you import any package from pika.dev

**TypeScript Version:** 4.0.0-dev.20200516
**Steps to reproduce crash**
1. Create a file and name it `mod.ts`
2. Paste this to it:
```ts
 import * as pkg from 'https://cdn.pika.dev/react@^16.13.1'
 console.log(pkg)
```
3. Run
`deno run ./mod.ts`

**TS Server Error Stack**
```
RangeError: Maximum call stack size exceeded
    at new URLSearchParams (internal/url.js:126:14)
    at URL.onParseComplete (internal/url.js:236:26)
    at parse (<anonymous>)
    at new URL (internal/url.js:319:5)
    at Function.create (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/hash_meta.js:78:43)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:19:43)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/home/igor/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
```

**Comment by Soremwar** [comment]
@IgorSzymanski This is not related, to Deno but to the extension you are using

Also, you are using a (pretty much) abandoned extension, use axetroy/deno until the official one is released(check the documentation for instructions on how to enable it, it won't enable by default)

If this helped please feel free to close this issue

**Comment by justjavac** [comment]
https://github.com/justjavac/typescript-deno-plugin/issues/39

**Comment by IgorSzymanski** [comment]
@justjavac Should I'm closing in favour of justjavac/typescript-deno-plugin#39.
