### ISSUE TITLE
Language server starts crashing while working on checker.ts in the TypeScript code base

### ISSUE THREAD

**Issue by dsherret** [denoland/vscode_deno#480]
This might be a duplicate. I'll investigate this later, but logging for now. Maybe I messed something up with my vscode while testing some stuff.

**Describe the bug**

I was doing some TypeScript changes and noticed the Deno language server running in the background constantly crashing.

**To Reproduce**

1. Clone and build the TypeScript compiler repo.
2. Open up checker.ts (swc is unable to parse this... I have an old bug in swc open)
3. Start typing stuff like `return (node as MetaProperty.`

Then this keeps repeating over and over:

```
Starting Deno language server...
  version: 1.12.2 (release, x86_64-pc-windows-msvc)
  executable: C:\Users\david\AppData\Local\bvm\binaries\denoland\deno\1.12.2\bin\deno.exe
Connected to "Visual Studio Code" 1.58.2
language server initialized
Server ready.
thread 'main' panicked at 'internal error: entered unreachable code: invalid pattern: Expr(Member(MemberExpr { span: Span { lo: BytePos(2468783), hi: BytePos(2468815), ctxt: #0 }, obj: Expr(Ident(Ident { span: Span { lo: BytePos(2468783), hi: BytePos(2468787), ctxt: #0 }, sym: Atom('node' type=inline), optional: false })), prop: Ident(Ident { span: Span { lo: BytePos(2468808), hi: BytePos(2468815), ctxt: #0 }, sym: Atom('default' type=static), optional: false }), computed: false }))', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\swc_ecma_parser-0.63.0\src\parser\expr.rs:1388:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 9:28:10 a.m.] Connection to server got closed. Server will restart.
[Error - 9:28:10 a.m.] Request textDocument/documentHighlight failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.7.0\client\node_modules\vscode-jsonrpc\lib\common\connection.js:1044:27)
    at Object.dispose (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.7.0\client\node_modules\vscode-languageclient\lib\common\client.js:73:35)
    at LanguageClient.handleConnectionClosed (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.7.0\client\node_modules\vscode-languageclient\lib\common\client.js:2424:42)
    at LanguageClient.handleConnectionClosed (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.7.0\client\node_modules\vscode-languageclient\lib\node\main.js:155:15)
    at closeHandler (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.7.0\client\node_modules\vscode-languageclient\lib\common\client.js:2411:18)
    at CallbackList.invoke (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.7.0\client\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
    at Emitter.fire (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.7.0\client\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
    at closeHandler (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.7.0\client\node_modules\vscode-jsonrpc\lib\common\connection.js:256:26)
    at CallbackList.invoke (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.7.0\client\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
    at Emitter.fire (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.7.0\client\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
    at StreamMessageReader.fireClose (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.7.0\client\node_modules\vscode-jsonrpc\lib\common\messageReader.js:40:27)
    at Socket.<anonymous> (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.7.0\client\node_modules\vscode-jsonrpc\lib\common\messageReader.js:125:42)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
```

**Expected behavior**

The Deno Language Server should not be doing anything because it's not in a deno initialized workspace.

**Versions**

vscode: 1.58.2 deno: 1.12.2 extension: 3.7.0

**Comment by kitsonk** [comment]
It is an incorrect assumption that the language server should do nothing. It still takes document updates and does dependency analysis, it just doesn't respond with diagnostics. Especially when supporting multi-root workspaces, the language server needs to watch things.

I agree it shouldn't panic. It is possible we can consider not doing dependency analysis if deno is not enabled, but then we need to determine a way to do it if the configuration changes and it is enabled.
