### ISSUE TITLE
Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by sant123** [denoland/vscode_deno#494]
**Describe the bug**
When clicking the `Run Test` code lens I get `Cannot read property 'toString' of null`

**To Reproduce**

1. Create a deno project with linter and unstable features
2. Create a `mod.test.ts` file
3. Fill it with this code

``` typescript
Deno.test({
  name: 'a test case',
  fn() {
    console.log('Foo!');
  },
});
```
4. You will see the `Run Test` above the pasted code.
5. Click it!

**Expected behavior**

The test should run.

**Screenshots**

![image](https://user-images.githubusercontent.com/7959437/129499770-5867a23b-ee13-4246-9c86-992ac4b084ad.png)

**Versions**

vscode: 1.59.0 deno: 1.13.0 extension: 3.8.0

**Comment by iugo** [comment]
macOS
VS Code 1.59.1

```
[renderer1] [error] Cannot read property 'toString' of null: TypeError: Cannot read property 'toString' of null
    at T.resolveOptions (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1531:5978)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async T.createTerminal (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1530:431)
    at async T.executeInTerminal (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1526:12764)
```

**Comment by kitsonk** [comment]
Yeah, I missed this, but yeah, I can reproduce too.  Not sure what happened. Investigating.
