### ISSUE TITLE
Extension cannot be activated(invalid parameters for "initialize" request)

### ISSUE THREAD

**Issue by attila-unitsold** [denoland/vscode_deno#495]
**Describe the bug**

After installing the extension it errors out immediately.

Deno Language Server Output:

```
invalid parameters for "initialize" request
[Error - 8:16:22 AM] Server initialization failed.
  Message: invalid type: map, expected a boolean
  Code: -32602 
[Error - 8:16:22 AM] Starting client failed
  Message: invalid type: map, expected a boolean
  Code: -32602 
```

Potentially relevant Extension Host log:

```
[2021-08-20 08:19:25.380] [exthost] [error] Activating extension denoland.vscode-deno failed due to an error:
[2021-08-20 08:19:25.380] [exthost] [error] Error: invalid type: map, expected a boolean
    at handleResponse (/Users/attila/.vscode/extensions/denoland.vscode-deno-3.8.0/client/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
    at processMessageQueue (/Users/attila/.vscode/extensions/denoland.vscode-deno-3.8.0/client/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
    at Immediate.<anonymous> (/Users/attila/.vscode/extensions/denoland.vscode-deno-3.8.0/client/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
    at processImmediate (internal/timers.js:461:21)
```

**To Reproduce**

1. install the extension from the marketplace
2. extension tries to start for the first time

**Versions**

vscode: 1.59.1 deno: 1.6.3 extension: 3.8.0

**Comment by kitsonk** [comment]
That is a very old version of Deno that doesn't support the version 3.8.0 of the extension.

What happens when you update your version of Deno?

**Comment by attila-unitsold** [comment]
Oho! So it turns out I had multiple deno versions installed, the one that ran was in ~/.deno/bin, it had priority over the one I installed via Homebrew yesterday. I ended up deleting ~/.deno completely, and now everything works, via deno 1.13.1. Thanks!
