### ISSUE TITLE
"Couldn't start client Deno Language Server"

### ISSUE THREAD

**Issue by harrysolovay** [denoland/vscode_deno#637]
**Describe the bug**

Unfortunately, I'm unsure of how to reproduce this error. It just started occurring after I uninstalled deno with Homebrew, and re-installed with the deno.land script (`curl -fsSL https://deno.land/x/install/install.sh | sh`). Please let me know what other information may be helpful to diagnosing.

Any help getting the LS working again would be greatly appreciated. Thank you!

 
<img width="473" alt="Screen Shot 2022-03-19 at 9 26 46 AM" src="https://user-images.githubusercontent.com/4893548/159123000-efa0a2d4-3186-4a3a-abe8-2c3a4483e1a7.png">

Extension host logs:

```
[2022-03-19 09:20:18.085] [exthost] [warning] DiagnosticCollection with name 'deno' does already exist.
[2022-03-19 09:20:18.089] [exthost] [error] Launching server using command deno failed. deno.restart {"value":"denoland.vscode-deno","_lower":"denoland.vscode-deno"}
```

Window logs:

```
[2022-03-19 09:19:56.937] [renderer1] [error] spawn deno ENOENT: Error: spawn deno ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[2022-03-19 09:20:18.094] [renderer1] [error] spawn deno ENOENT: Error: spawn deno ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Versions**

vscode: 1.65.2 (Universal)
deno: 1.20.1
extension: 3.10.1

**Comment by harrysolovay** [comment]
The error went away. Not sure what cause it. Apologies for the noise :)

**Comment by harrysolovay** [comment]
It's occurring again :/ any tips would be greatly appreciated!

**Comment by kitsonk** [comment]
The error you are experiencing is a strong indicator that it is a specific environment issue.  Specifically `ENOENT` indicates that vscode cannot find the Deno binary.  So likely the environment you are launching vscode in does not include the `deno` executable in its path, but when you do, it works. As you mention, you re-installed/re-located the executable, which likely caused this disconnect.

You can try to see if this is the case by setting `"deno.path"` to the path of the executable in your settings, and if the problem goes away, then it even more of a clear indicator that the environment you are starting vscode from does not have a consistent PATH for discovery of the executable.

**Comment by harrysolovay** [comment]
You're absolutely correct! I explicitly set the path in my VSCode settings & it's now working well! Thank you Kitson!
