### ISSUE TITLE
can't resolve wsl paths on windows10

### ISSUE THREAD

**Issue by alf-ytakada** [denoland/vscode_deno#73]
Hi!

I'm using vscode on windows10.
My project is located in the wsl2 directory.

# issue

when I use modules with URL, an error has occurred.

typescript server log is here.

```
Info 70   [21:46:3.354] [typescript-deno-plugin] baseUrl: file:///wsl$/Ubuntu-20.04/home/path/to/project/
Info 71   [21:46:3.354] [typescript-deno-plugin] module "https://deno.land/std@v0.52.0/path/mod.ts" can not resolved
```

and relative path's error log is,

```


Info 75   [21:46:3.355] [typescript-deno-plugin] moduleName: ../util.ts
Info 76   [21:46:3.355] [typescript-deno-plugin] e: TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute
    at getPathFromURLWin32 (internal/url.js:1310:13)
    at Object.fileURLToPath (internal/url.js:1342:22)
    at parseModuleName (C:\Users\xxx\.vscode\extensions\denoland.vscode-deno-1.24.0\node_modules\typescript-deno-plugin\out\index.js:331:30)
    at ConfiguredProject.tsLsHost.resolveModuleNames (C:\Users\xxx\.vscode\extensions\denoland.vscode-deno-1.24.0\node_modules\typescript-deno-plugin\out\index.js:95:50)
    at Object.compilerHost.resolveModuleNames (c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:135192:52)
    at resolveModuleNamesWorker (c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97713:127)
    at resolveModuleNamesReusingOldState (c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97983:24)
    at processImportedModules (c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99448:35)
    at findSourceFile (c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99191:17)
    at c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:85
    at getSourceFileFromReferenceWorker (c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98987:34)
    at processSourceFile (c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:13)
    at processRootFile (c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98843:13)
    at c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97809:60
    at Object.forEach (c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at Object.createProgram (c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97809:16)
    at synchronizeHostData (c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:135218:26)
    at Object.getProgram (c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:135310:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:139786:53)
    at ConfiguredProject.Project.updateGraph (c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:139729:42)
    at ConfiguredProject.updateGraph (c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:140654:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:142246:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143101:44)
    at c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143396:107
    at Object.mapDefined (c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143396:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:144260:46)
    at c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:145994:28)
    at IOSession.Session.executeCommand (c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146003:33)
    at IOSession.Session.onMessage (c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146027:35)
    at Interface.<anonymous> (c:\tools\VSCode-win32-x64\resources\app\extensions\node_modules\typescript\lib\tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

Do you have any solutions?

**Comment by nayeemrmn** [comment]
Are you using this extention: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl? You should, and then install this extension on the Linux side.

**Comment by alf-ytakada** [comment]
@nayeemrmn 
correct!
I aliases my command like this.

```
$ alias code
alias code='/mnt/c/tools/VSCode-win32-x64/Code.exe
```
I had completely forgotten about it.
I take my hat off to you. Thank you!
