### ISSUE TITLE
Type of re-exported code not correctly detected from npm packages

### ISSUE THREAD

**Issue by spencerhakim** [denoland/vscode_deno#756]
**Describe the bug**

The Deno extension doesn't correctly detect the type of re-exported functions/object/etc from npm packages, like so:

```js
export { a, b, c } from './another-file';
export { d, e, f } from 'another-package';
```

This results in errors failing to be reported in the UI and a lack of type information being presented to the developer.

**To Reproduce**

Write any code that uses re-exported functions/objects/etc, and you'll see something like the following:
![Deno Example](https://user-images.githubusercontent.com/606857/205705379-0e945e8b-4499-4d45-acf9-108f9dee9061.jpg)

**Expected behavior**

The types of the code being used should be correctly detected and any errors reported, as it does in a standard Node project:
![Node Example](https://user-images.githubusercontent.com/606857/205705523-89f5382f-26e0-410e-b513-e1e8aed3ff07.jpg)

**Versions**

vscode: 1.73.1 deno: 1.28.3 extension: 3.14.1

**Comment by bartlomieju** [comment]
CC @dsherret

**Comment by dsherret** [comment]
@spencerhakim could you post some full reproduction code? I'm not able to reproduce. Thanks!

**Comment by dsherret** [comment]
Just noticed the package name in the screenshots and this is a npm:postgraphile specific issue. Reproduction steps:

```ts
// main.ts
import { createPostGraphileSchema } from "npm:postgraphile";

createPostGraphileSchema();
```

```
> deno check --remote main.ts
error: TS2580 [ERROR]: Cannot find name 'Buffer'.
    readonly chunk: Buffer;
                    ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/messages.d.ts:58:21 

TS2580 [ERROR]: Cannot find name 'Buffer'.
    constructor(length: number, chunk: Buffer);
                                       ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/messages.d.ts:60:40 

TS2580 [ERROR]: Cannot find name 'Buffer'.
    readonly salt: Buffer;
                   ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/messages.d.ts:102:20

TS2580 [ERROR]: Cannot find name 'Buffer'.
    constructor(length: number, salt: Buffer);
                                      ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/messages.d.ts:104:39

TS2580 [ERROR]: Cannot find name 'Buffer'.
    startup: (opts: Record<string, string>) => Buffer;
                                               ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/serializer.d.ts:24:48

TS2580 [ERROR]: Cannot find name 'Buffer'.
    password: (password: string) => Buffer;
                                    ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/serializer.d.ts:25:37

TS2580 [ERROR]: Cannot find name 'Buffer'.
    requestSsl: () => Buffer;
                      ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/serializer.d.ts:26:23

TS2580 [ERROR]: Cannot find name 'Buffer'.
    sendSASLInitialResponseMessage: (mechanism: string, initialResponse: string) => Buffer;
                                                                                    ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/serializer.d.ts:27:85

TS2580 [ERROR]: Cannot find name 'Buffer'.
    sendSCRAMClientFinalMessage: (additionalData: string) => Buffer;
                                                             ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/serializer.d.ts:28:62

TS2580 [ERROR]: Cannot find name 'Buffer'.
    query: (text: string) => Buffer;
                             ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/serializer.d.ts:29:30

TS2580 [ERROR]: Cannot find name 'Buffer'.
    parse: (query: ParseOpts) => Buffer;
                                 ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/serializer.d.ts:30:34

TS2580 [ERROR]: Cannot find name 'Buffer'.
    bind: (config?: BindOpts) => Buffer;
                                 ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/serializer.d.ts:31:34

TS2580 [ERROR]: Cannot find name 'Buffer'.
    execute: (config?: ExecOpts | undefined) => Buffer;
                                                ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/serializer.d.ts:32:49

TS2580 [ERROR]: Cannot find name 'Buffer'.
    describe: (msg: PortalOpts) => Buffer;
                                   ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/serializer.d.ts:33:36

TS2580 [ERROR]: Cannot find name 'Buffer'.
    close: (msg: PortalOpts) => Buffer;
                                ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/serializer.d.ts:34:33

TS2580 [ERROR]: Cannot find name 'Buffer'.
    flush: () => Buffer;
                 ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/serializer.d.ts:35:18

TS2580 [ERROR]: Cannot find name 'Buffer'.
    sync: () => Buffer;
                ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/serializer.d.ts:36:17

TS2580 [ERROR]: Cannot find name 'Buffer'.
    end: () => Buffer;
               ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/serializer.d.ts:37:16

TS2580 [ERROR]: Cannot find name 'Buffer'.
    copyData: (chunk: Buffer) => Buffer;
                      ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/serializer.d.ts:38:23

TS2580 [ERROR]: Cannot find name 'Buffer'.
    copyData: (chunk: Buffer) => Buffer;
                                 ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/serializer.d.ts:38:34

TS2580 [ERROR]: Cannot find name 'Buffer'.
    copyDone: () => Buffer;
                    ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/serializer.d.ts:39:21

TS2580 [ERROR]: Cannot find name 'Buffer'.
    copyFail: (message: string) => Buffer;
                                   ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/serializer.d.ts:40:36

TS2580 [ERROR]: Cannot find name 'Buffer'.
    cancel: (processID: number, secretKey: number) => Buffer;
                                                      ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/serializer.d.ts:41:55

TS2580 [ERROR]: Cannot find name 'Buffer'.
    packet: Buffer;
            ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/parser.d.ts:6:13

TS2580 [ERROR]: Cannot find name 'Buffer'.
    parse(buffer: Buffer, callback: MessageCallback): void;
                  ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/parser.d.ts:19:19

TS2580 [ERROR]: Cannot find name 'Buffer'.
    parseAuthenticationResponse(offset: number, length: number, bytes: Buffer): any;
                                                                       ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/parser.d.ts:35:72

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
export declare function parse(stream: NodeJS.ReadableStream, callback: MessageCallback): Promise<void>;
                                      ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/pg-protocol/1.5.0/dist/index.d.ts:5:39

TS2580 [ERROR]: Cannot find name 'Buffer'.
    values?: Array<Buffer | null | undefined | string> | undefined;
                   ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/pg/8.6.5/index.d.ts:126:20

TS2580 [ERROR]: Cannot find name 'Buffer'.
    on(event: "ping" | "pong", listener: (this: WebSocket, data: Buffer) => void): this;
                                                                 ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/ws/7.4.7/index.d.ts:126:66

TS2580 [ERROR]: Cannot find name 'Buffer'.
    once(event: "ping" | "pong", listener: (this: WebSocket, data: Buffer) => void): this;
                                                                   ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/ws/7.4.7/index.d.ts:138:68

TS2580 [ERROR]: Cannot find name 'Buffer'.
    off(event: "ping" | "pong", listener: (this: WebSocket, data: Buffer) => void): this;
                                                                  ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/ws/7.4.7/index.d.ts:150:67

TS2580 [ERROR]: Cannot find name 'Buffer'.
    addListener(event: "ping" | "pong", listener: (data: Buffer) => void): this;
                                                         ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/ws/7.4.7/index.d.ts:162:58

TS2580 [ERROR]: Cannot find name 'Buffer'.
    removeListener(event: "ping" | "pong", listener: (data: Buffer) => void): this;
                                                            ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/ws/7.4.7/index.d.ts:174:61

TS2580 [ERROR]: Cannot find name 'Buffer'.
    type Data = string | Buffer | ArrayBuffer | Buffer[];
                         ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/ws/7.4.7/index.d.ts:186:26

TS2580 [ERROR]: Cannot find name 'Buffer'.
    type Data = string | Buffer | ArrayBuffer | Buffer[];
                                                ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/ws/7.4.7/index.d.ts:186:49

TS2580 [ERROR]: Cannot find name 'Buffer'.
    type CertMeta = string | string[] | Buffer | Buffer[];
                                        ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/ws/7.4.7/index.d.ts:191:41

TS2580 [ERROR]: Cannot find name 'Buffer'.
    type CertMeta = string | string[] | Buffer | Buffer[];
                                                 ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/ws/7.4.7/index.d.ts:191:50

TS2580 [ERROR]: Cannot find name 'Buffer'.
            dictionary?: Buffer | Buffer[] | DataView | undefined;
                         ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/ws/7.4.7/index.d.ts:241:26

TS2580 [ERROR]: Cannot find name 'Buffer'.
            dictionary?: Buffer | Buffer[] | DataView | undefined;
                                  ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/ws/7.4.7/index.d.ts:241:35

TS2580 [ERROR]: Cannot find name 'Buffer'.
            upgradeHead: Buffer,
                         ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/ws/7.4.7/index.d.ts:312:26

TS2580 [ERROR]: Cannot find name 'Buffer'.
    end(moreBody?: Buffer | string | null): void;
                   ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/postgraphile/4.12.12/build/postgraphile/http/frameworks.d.ts:58:20

TS2580 [ERROR]: Cannot find name 'Buffer'.
    abstract setBody(body: Stream | Buffer | string | undefined): void;
                                    ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/postgraphile/4.12.12/build/postgraphile/http/frameworks.d.ts:65:37

TS2580 [ERROR]: Cannot find name 'Buffer'.
    setBody(body: Stream | Buffer | string | undefined): void;
                           ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/postgraphile/4.12.12/build/postgraphile/http/frameworks.d.ts:79:28

TS2580 [ERROR]: Cannot find name 'Buffer'.
    setBody(body: Stream | Buffer | string | undefined): void;
                           ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/postgraphile/4.12.12/build/postgraphile/http/frameworks.d.ts:94:28

TS2580 [ERROR]: Cannot find name 'Buffer'.
    setBody(body: Stream | Buffer | string | undefined): void;
                           ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/postgraphile/4.12.12/build/postgraphile/http/frameworks.d.ts:108:28

TS2580 [ERROR]: Cannot find name 'Buffer'.
    | Buffer
      ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/jsonwebtoken/8.5.9/index.d.ts:160:7

TS2580 [ERROR]: Cannot find name 'Buffer'.
    | { key: string | Buffer; passphrase: string };
                      ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/jsonwebtoken/8.5.9/index.d.ts:161:23

TS2580 [ERROR]: Cannot find name 'Buffer'.
    payload: string | Buffer | object,
                      ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/jsonwebtoken/8.5.9/index.d.ts:171:23

TS2580 [ERROR]: Cannot find name 'Buffer'.
    payload: string | Buffer | object,
                      ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/jsonwebtoken/8.5.9/index.d.ts:184:23

TS2580 [ERROR]: Cannot find name 'Buffer'.
    payload: string | Buffer | object,
                      ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/jsonwebtoken/8.5.9/index.d.ts:189:23

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'Plugin'.
import { Plugin, PostGraphileCoreOptions } from 'postgraphile-core';
         ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/postgraphile/4.12.12/build/interfaces.d.ts:6:10

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'PostGraphileCoreOptions'.
import { Plugin, PostGraphileCoreOptions } from 'postgraphile-core';
                 ~~~~~~~~~~~~~~~~~~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/postgraphile/4.12.12/build/interfaces.d.ts:6:18

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'createPostGraphileSchema'.
export { createPostGraphileSchema, watchPostGraphileSchema } from 'postgraphile-core';
         ~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/postgraphile/4.12.12/build/postgraphile/index.d.ts:3:10

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'watchPostGraphileSchema'.
export { createPostGraphileSchema, watchPostGraphileSchema } from 'postgraphile-core';
                                   ~~~~~~~~~~~~~~~~~~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/postgraphile/4.12.12/build/postgraphile/index.d.ts:3:36

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'Plugin'.
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/postgraphile/4.12.12/build/index.d.ts:3:10

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'Build'.
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/postgraphile/4.12.12/build/index.d.ts:3:18

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'Context'.
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/postgraphile/4.12.12/build/index.d.ts:3:25

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'SchemaBuilder'.
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/postgraphile/4.12.12/build/index.d.ts:3:34

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'SchemaListener'.
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/postgraphile/4.12.12/build/index.d.ts:3:49

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'Inflection'.
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/postgraphile/4.12.12/build/index.d.ts:3:65

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'Options'.
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/postgraphile/4.12.12/build/index.d.ts:3:77

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'postGraphileBaseOverrides'.
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/postgraphile/4.12.12/build/index.d.ts:3:86

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'postGraphileClassicIdsOverrides'.
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/postgraphile/4.12.12/build/index.d.ts:3:113

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'PostGraphileInflectionPlugin'.
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/postgraphile/4.12.12/build/index.d.ts:3:146

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'PostGraphileClassicIdsInflectionPlugin'.
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/postgraphile/4.12.12/build/index.d.ts:3:176

Found 65 errors.
```
