### ISSUE TITLE
WSL2 Failed to load node_modules for typescript support.

### ISSUE THREAD

**Issue by GustavoFenilli** [denoland/vscode_deno#82]
**Error:**

The extensions doesn't seen to work at all, doesn't have intellisense nor error ignore for .ts files.

```
Info 29   [21:46:3.563] Failed to load module 'typescript-deno-plugin' from /home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/typescript-language-features/node_modules: Error: Could not resolve JS module 'typescript-deno-plugin' starting at '/home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/typescript-language-features/node_modules'. Looked in: /home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/typescript-language-features/node_modules/typescript-deno-plugin/package.json, /home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/typescript-language-features/node_modules/typescript-deno-plugin.js, /home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/typescript-language-features/node_modules/typescript-deno-plugin.jsx, /home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/typescript-language-features/node_modules/typescript-deno-plugin/index.js, /home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/typescript-language-features/node_modules/typescript-deno-plugin/index.jsx, /home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript-deno-plugin/package.json, /home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript-deno-plugin.js, /home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript-deno-plugin.jsx, /home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript-deno-plugin/index.js, /home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript-deno-plugin/index.jsx, /home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/node_modules/typescript-deno-plugin/package.json, /home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/node_modules/typescript-deno-plugin.js, /home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/node_modules/typescript-deno-plugin.jsx, /home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/node_modules/typescript-deno-plugin/index.js, /home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/node_modules/typescript-deno-plugin/index.jsx, /home/fenilli/.vscode-server/bin/node_modules/typescript-deno-plugin/package.json, /home/fenilli/.vscode-server/bin/node_modules/typescript-deno-plugin.js, /home/fenilli/.vscode-server/bin/node_modules/typescript-deno-plugin.jsx, /home/fenilli/.vscode-server/bin/node_modules/typescript-deno-plugin/index.js, /home/fenilli/.vscode-server/bin/node_modules/typescript-deno-plugin/index.jsx, /home/fenilli/.vscode-server/node_modules/typescript-deno-plugin/package.json, /home/fenilli/.vscode-server/node_modules/typescript-deno-plugin.js, /home/fenilli/.vscode-server/node_modules/typescript-deno-plugin.jsx, /home/fenilli/.vscode-server/node_modules/typescript-deno-plugin/index.js, /home/fenilli/.vscode-server/node_modules/typescript-deno-plugin/index.jsx, /home/fenilli/node_modules/typescript-deno-plugin/package.json, /home/fenilli/node_modules/typescript-deno-plugin.js, /home/fenilli/node_modules/typescript-deno-plugin.jsx, /home/fenilli/node_modules/typescript-deno-plugin/index.js, /home/fenilli/node_modules/typescript-deno-plugin/index.jsx, /home/node_modules/typescript-deno-plugin/package.json, /home/node_modules/typescript-deno-plugin.js, /home/node_modules/typescript-deno-plugin.jsx, /home/node_modules/typescript-deno-plugin/index.js, /home/node_modules/typescript-deno-plugin/index.jsx, /node_modules/typescript-deno-plugin/package.json, /node_modules/typescript-deno-plugin.js, /node_modules/typescript-deno-plugin.jsx, /node_modules/typescript-deno-plugin/index.js, /node_modules/typescript-deno-plugin/index.jsx
    at Object.resolveJSModule (/home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript/lib/tsserver.js:29284:19)
    at Object.sys.require (/home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript/lib/tsserver.js:147642:45)
    at Function.Project.resolveModule (/home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript/lib/tsserver.js:139196:35)
    at /home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript/lib/tsserver.js:140205:36
    at Object.firstDefined (/home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript/lib/tsserver.js:197:26)
    at InferredProject.Project.enablePlugin (/home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript/lib/tsserver.js:140204:41)
    at _loop_2 (/home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript/lib/tsserver.js:140188:32)
    at InferredProject.Project.enableGlobalPlugins (/home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript/lib/tsserver.js:140194:25)
    at new InferredProject (/home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript/lib/tsserver.js:140365:23)
    at ProjectService.createInferredProject (/home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript/lib/tsserver.js:142495:31)
    at ProjectService.getOrCreateInferredProjectForProjectRootPathIfEnabled (/home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript/lib/tsserver.js:142433:33)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript/lib/tsserver.js:141690:36)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript/lib/tsserver.js:143132:26)
    at /home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript/lib/tsserver.js:143396:107
    at Object.mapDefined (/home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript/lib/tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (/home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript/lib/tsserver.js:143396:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript/lib/tsserver.js:144260:46)
    at /home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript/lib/tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (/home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript/lib/tsserver.js:145994:28)
    at IOSession.Session.executeCommand (/home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript/lib/tsserver.js:146003:33)
    at IOSession.Session.onMessage (/home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript/lib/tsserver.js:146027:35)
    at Interface.<anonymous> (/home/fenilli/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/node_modules/typescript/lib/tsserver.js:147342:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```
**Expected:**

Supressing error with .ts and finding modules from urls.

**Comment by GustavoFenilli** [comment]
Fixed #80 updating to V1.46.0 works now.
