### ISSUE TITLE
package.json auto-resolved despite not being in deno.enablePaths

### ISSUE THREAD

**Issue by evelant** [denoland/vscode_deno#838]
**Describe the bug**

**To Reproduce**

1. set `deno.enablePaths` to some sub-directory of a project that has a root package.json
2. Observe deno language server output `Auto-resolved package.json: "file:///Path/to/project/package.json"` even though this is outside of `enablePaths`

I don't want the deno plugin to use this package.json but there appears to be no way to prevent this behavior. If there is a root package.json it gets auto-detected and used no matter what.

Specifically this is likely to impact every Supabase project.

**Expected behavior**

Deno plugin should not automatically pick up a package.json if it is not encluded in `deno.enablePaths`

**Screenshots**

N/A

**Versions**

vscode: 1.77.3 deno: 1.31.0  extension: 3.17.0

**Comment by evelant** [comment]
I'm also seeing a lot of this

```
Failed to request to tsserver Error: Could not find source file: 'asset:///lib.deno.console.d.ts'.
    at getValidSourceFile (ext:deno_tsc/00_typescript.js:133358:23)
    at Object.getEncodedSemanticClassifications3 [as getEncodedSemanticClassifications] (ext:deno_tsc/00_typescript.js:133880:106)
    at serverRequest (ext:deno_tsc/99_main_compiler.js:1092:27)
    at [ext:cli/lsp/tsc.rs:3496:26]:1:12
[Error - 3:22:11 PM] Request textDocument/semanticTokens/full failed.
  Message: Invalid request
  Code: -32600 
Failed to request to tsserver Error: Could not find source file: 'asset:///lib.deno.ns.d.ts'.
    at getValidSourceFile (ext:deno_tsc/00_typescript.js:133358:23)
    at Object.getEncodedSemanticClassifications3 [as getEncodedSemanticClassifications] (ext:deno_tsc/00_typescript.js:133880:106)
    at serverRequest (ext:deno_tsc/99_main_compiler.js:1092:27)
    at [ext:cli/lsp/tsc.rs:3496:26]:1:12
client asked to cancel request 1387, but no such pending request exists, ignoring
[Error - 3:22:11 PM] Request textDocument/semanticTokens/full failed.
  Message: Invalid request
  Code: -32600 
Failed to request to tsserver Error: Could not find source file: 'asset:///lib.deno.web.d.ts'.
    at getValidSourceFile (ext:deno_tsc/00_typescript.js:133358:23)
    at Object.getEncodedSemanticClassifications3 [as getEncodedSemanticClassifications] (ext:deno_tsc/00_typescript.js:133880:106)
    at serverRequest (ext:deno_tsc/99_main_compiler.js:1092:27)
    at [ext:cli/lsp/tsc.rs:3496:26]:1:12
[Error - 3:22:12 PM] Request textDocument/semanticTokens/full failed.
  Message: Invalid request
  Code: -32600 
```

It appears that the Deno extension is fighting with tsserver somehow. Type checking and quick docs will work for ~30 seconds then all Deno specific stuff will get highlighted as an error. My Deno files are excluded from my root tsconfig so they should only be processed through the Deno language server.

**Comment by evelant** [comment]
I'm still at a loss for what's going wrong here. I specifically made sure that all of my Deno files are in the excludes for my root tsconfig.json. I've also made sure that `typescript.tsserver.experimental.enableProjectDiagnostics` is `false` and I only have one folder in `"deno.enablePaths"`. 

Despite this vscode_deno still says it auto-detected my root package.json. Errors are highlighted and then disappear in Deno files every 1-3 seconds. The Deno Language Server output continually outputs messages when this is happening like so:

```
successfully cancelled request with ID: 4454
successfully cancelled request with ID: 4455
Unable to send result to client.
successfully cancelled request with ID: 4453
successfully cancelled request with ID: 4457
client asked to cancel request 4287, but no such pending request exists, ignoring
client asked to cancel request 4133, but no such pending request exists, ignoring
Unable to send result to client.
Unable to send result to client.
Unable to send result to client.
Unable to send result to client.
client asked to cancel request 4459, but no such pending request exists, ignoring
client asked to cancel request 4460, but no such pending request exists, ignoring
successfully cancelled request with ID: 4493
Unable to send result to client.
successfully cancelled request with ID: 4536
client asked to cancel request 4450, but no such pending request exists, ignoring
client asked to cancel request 4494, but no such pending request exists, ignoring
successfully cancelled request with ID: 4539
client asked to cancel request 4132, but no such pending request exists, ignoring
Unable to send result to client.
successfully cancelled request with ID: 4541
successfully cancelled request with ID: 4540
successfully cancelled request with ID: 4544
successfully cancelled request with ID: 4543
client asked to cancel request 4461, but no such pending request exists, ignoring
Unable to send result to client.
Unable to send result to client.
Unable to send result to client.
Unable to send result to client.
Unable to send result to client.
successfully cancelled request with ID: 4553
Unable to send result to client.
successfully cancelled request with ID: 4557
Unable to send result to client.
successfully cancelled request with ID: 4563
Unable to send result to client.
client asked to cancel request 4564, but no such pending request exists, ignoring
successfully cancelled request with ID: 4579
client asked to cancel request 4580, but no such pending request exists, ignoring
Unable to send result to client.
client asked to cancel request 4555, but no such pending request exists, ignoring
successfully cancelled request with ID: 4583
Unable to send result to client.
client asked to cancel request 4586, but no such pending request exists, ignoring
client asked to cancel request 4585, but no such pending request exists, ignoring
successfully cancelled request with ID: 4587
Unable to send result to client.
client asked to cancel request 4590, but no such pending request exists, ignoring
client asked to cancel request 4589, but no such pending request exists, ignoring
successfully cancelled request with ID: 4591
Unable to send result to client.
client asked to cancel request 4596, but no such pending request exists, ignoring
client asked to cancel request 4597, but no such pending request exists, ignoring
client asked to cancel request 4608, but no such pending request exists, ignoring
client asked to cancel request 4609, but no such pending request exists, ignoring
client asked to cancel request 4620, but no such pending request exists, ignoring
client asked to cancel request 4592, but no such pending request exists, ignoring
client asked to cancel request 4621, but no such pending request exists, ignoring
successfully cancelled request with ID: 4646
client asked to cancel request 4632, but no such pending request exists, ignoring
successfully cancelled request with ID: 4649
successfully cancelled request with ID: 4650
successfully cancelled request with ID: 4651
successfully cancelled request with ID: 4648
successfully cancelled request with ID: 4652
client asked to cancel request 4633, but no such pending request exists, ignoring
Unable to send result to client.
Unable to send result to client.
Unable to send result to client.
Unable to send result to client.
Unable to send result to client.
client asked to cancel request 4647, but no such pending request exists, ignoring
client asked to cancel request 4654, but no such pending request exists, ignoring
successfully cancelled request with ID: 4666
successfully cancelled request with ID: 4667
successfully cancelled request with ID: 4668
successfully cancelled request with ID: 4669
successfully cancelled request with ID: 4671
successfully cancelled request with ID: 4672
Unable to send result to client.
Unable to send result to client.
Unable to send result to client.
Unable to send result to client.
Unable to send result to client.
Unable to send result to client.
client asked to cancel request 4673, but no such pending request exists, ignoring
successfully cancelled request with ID: 4674
successfully cancelled request with ID: 4675
successfully cancelled request with ID: 4676
client asked to cancel request 3946, but no such pending request exists, ignoring
client asked to cancel request 3947, but no such pending request exists, ignoring
successfully cancelled request with ID: 4677
successfully cancelled request with ID: 4680
successfully cancelled request with ID: 4681
client asked to cancel request 4670, but no such pending request exists, ignoring
successfully cancelled request with ID: 4683
client asked to cancel request 4653, but no such pending request exists, ignoring
successfully cancelled request with ID: 4684
successfully cancelled request with ID: 4685
successfully cancelled request with ID: 4687
successfully cancelled request with ID: 4686
Unable to send result to client.
Unable to send result to client.
Unable to send result to client.
Unable to send result to client.
Unable to send result to client.
Unable to send result to client.
Unable to send result to client.
Unable to send result to client.
Unable to send result to client.
Unable to send result to client.
successfully cancelled request with ID: 4720
successfully cancelled request with ID: 4722
client asked to cancel request 4682, but no such pending request exists, ignoring
client asked to cancel request 4678, but no such pending request exists, ignoring
successfully cancelled request with ID: 4727
successfully cancelled request with ID: 4728
successfully cancelled request with ID: 4729
Unable to send result to client.
Unable to send result to client.
Unable to send result to client.
client asked to cancel request 4748, but no such pending request exists, ignoring
successfully cancelled request with ID: 4785
Unable to send result to client.
successfully cancelled request with ID: 4804
Unable to send result to client.
successfully cancelled request with ID: 4806
Unable to send result to client.
client asked to cancel request 4807, but no such pending request exists, ignoring
```

**Comment by dsherret** [comment]
@evelant It's expected that deno will still auto-resolve the package.json. It won't use it though unless there is a bare specifier that matches what's in the package.json.

Given that you are hitting the document preload limit of 1000 when there is a deno.enablePaths for a folder with only 20 directories, it sounds like there might be a bug in the filtering or it is configured incorrectly. What does your project structure look like and what does the vscode config for that workspace look like?
