### ISSUE TITLE
(Unsure of source of bug) TS Server fatal error:  Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by AbhinavRobinson** [denoland/vscode_deno#85]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.9.4
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
TypeError: Cannot read property 'get' of undefined
    at resolveModuleNamesReusingOldState (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:100222:92)
    at processImportedModules (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101668:35)
    at findSourceFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101411:17)
    at /root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:99987:60
    at Object.forEach (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at Object.createProgram (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:99987:16)
    at synchronizeHostData (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:138726:26)
    at Object.getProgram (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:138818:13)
    at InferredProject.Project.updateGraphWorker (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:143310:53)
    at InferredProject.Project.updateGraph (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:143253:42)
    at updateProjectIfDirty (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:144517:45)
    at Array.forEach (<anonymous>)
    at ProjectService.assignProjectToOpenedScriptInfo (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:146631:41)
    at /root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:146900:97
    at Object.flatMap (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:465:25)
    at ProjectService.applyChangesInOpenFiles (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:146900:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:147763:46)
    at /root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:149526:88
    at IOSession.Session.executeWithRequestId (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:149517:28)
    at IOSession.Session.executeCommand (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:149526:33)
    at IOSession.Session.onMessage (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:149550:35)
    at Interface.<anonymous> (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:150866:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

Extension version: 1.25.0
VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.53GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+UbuntuOnD/mnt/c/Users/HP/Desktop/Code/deno --remote=wsl+UbuntuOnD|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: UbuntuOnD|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|15.88GB (8.53GB free)|
|VM|0%|
</details>

**Comment by AbhinavRobinson** [comment]
I encountered this right after installing the plugin for vscode.

**Comment by lucacasonato** [comment]
This issue should be resolved now. If it is not, please open a new issue :-)
