### ISSUE TITLE
Getting "command 'x' already exists" errors when switching deno versions or restarting lsp

### ISSUE THREAD

**Issue by dsherret** [denoland/vscode_deno#985]
I'm not exactly sure the reproduction steps. In this case, I had one canary version of Deno and then I upgraded to a new canary version of Deno then I get errors like `command 'deno.reloadImportRegistries' already exists`. The fix is to restart vscode.

```
Starting Deno language server...
  version: 1.37.1+8d24be1 (release, x86_64-pc-windows-msvc)
  executable: C:\Users\david\.deno\bin\deno.EXE
Connected to "Visual Studio Code" 1.83.1
Enabling import suggestions for: https://deno.land
Server ready.
[Info  - 12:35:05 PM] Connection to server got closed. Server will restart.
Starting Deno language server...
  version: 1.37.2+be97170 (release, x86_64-pc-windows-msvc)
  executable: C:\Users\david\.deno\bin\deno.EXE
Connected to "Visual Studio Code" 1.83.1
Enabling import suggestions for: https://deno.land
[Error - 12:35:06 PM] Server initialization failed.
Error: command 'deno.reloadImportRegistries' already exists
    at n.registerCommand (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:125:82889)
    at Object.registerCommand (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:140:20485)
    at ExecuteCommandFeature.register (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.26.0\client\dist\main.js:15050:48)
    at ExecuteCommandFeature.initialize (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.26.0\client\dist\main.js:15030:14)
    at LanguageClient2.initializeFeatures (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.26.0\client\dist\main.js:17711:19)
    at LanguageClient2.doInitialize (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.26.0\client\dist\main.js:17288:16)
    at LanguageClient2.start (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.26.0\client\dist\main.js:17185:11)
[Error - 12:35:06 PM] Deno Language Server client: couldn't create connection to server.
Error: command 'deno.reloadImportRegistries' already exists
    at n.registerCommand (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:125:82889)
    at Object.registerCommand (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:140:20485)
    at ExecuteCommandFeature.register (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.26.0\client\dist\main.js:15050:48)
    at ExecuteCommandFeature.initialize (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.26.0\client\dist\main.js:15030:14)
    at LanguageClient2.initializeFeatures (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.26.0\client\dist\main.js:17711:19)
    at LanguageClient2.doInitialize (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.26.0\client\dist\main.js:17288:16)
    at LanguageClient2.start (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.26.0\client\dist\main.js:17185:11)
[Error - 12:35:06 PM] Restarting server failed
Error: command 'deno.reloadImportRegistries' already exists
    at n.registerCommand (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:125:82889)
    at Object.registerCommand (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:140:20485)
    at ExecuteCommandFeature.register (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.26.0\client\dist\main.js:15050:48)
    at ExecuteCommandFeature.initialize (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.26.0\client\dist\main.js:15030:14)
    at LanguageClient2.initializeFeatures (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.26.0\client\dist\main.js:17711:19)
    at LanguageClient2.doInitialize (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.26.0\client\dist\main.js:17288:16)
    at LanguageClient2.start (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.26.0\client\dist\main.js:17185:11)
Server ready.
[Info  - 12:35:08 PM] Connection to server got closed. Server will restart.
```

**Comment by nayeemrmn** [comment]
This is a dated compat issue from when the command existed on both the server and extension.
